language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

before_install: 
  - "cd {{cookiecutter.app_slug}}"

install:
  - "pip install pipenv"
  - "pipenv install --dev"

script:
  - python manage.py cov
